DEEPSORT:
  REID_CKPT: "E:\\graduation thesis\\MTMCT\\code modification\\deep_sort_pytorch-master - Vehicle - Multi\\deep_sort_pytorch-master\\deep_sort\\deep\\checkpoint\\ckpt_car.t7"
  #REID_CKPT: "./deep_sort/deep/checkpoint/model.pkl"
  # MAX_DIST: 0.2
  MAX_DIST: 0.1
  MIN_CONFIDENCE: 0.3
  NMS_MAX_OVERLAP: 0.5
  MAX_IOU_DISTANCE: 0.7
  MAX_AGE: 70
  N_INIT: 3
  NN_BUDGET: 100
  #FLAG: False
  