YOLOV3:
  CFG: "E:\\graduation thesis\\MTMCT\\code modification\\deep_sort_pytorch-master - Vehicle - Multi\\deep_sort_pytorch-master\\detector\\YOLOv3\\cfg\\yolo_v3.cfg"
  WEIGHT: "E:\\graduation thesis\\MTMCT\\code modification\\deep_sort_pytorch-master - Vehicle - Multi\\deep_sort_pytorch-master\\detector\\YOLOv3\\weight\\yolov3.weights"
  CLASS_NAMES: "E:\\graduation thesis\\MTMCT\\code modification\\deep_sort_pytorch-master - Vehicle - Multi\\deep_sort_pytorch-master\\detector\\YOLOv3\\cfg\\coco.names"

  SCORE_THRESH: 0.5
  NMS_THRESH: 0.4
